services:
  kratos-admin-ui:
    build: .
    ports:
      - 3000:8080
    environment:
      - KRATOS_ADMIN_URL=http://host.docker.internal:4434
      - KRATOS_PUBLIC_URL=http://host.docker.internal:4433